In [1]:
import numpy as np

Creating a matrix using numpy

In [3]:
matrix1 = np.array([[2,3],[6,7]])
print(matrix1)

[[2 3]
 [6 7]]


In [5]:
matrix1.shape

(2, 2)

In [6]:
matrix2 = np.array([[10,35,45], [50,64,80],[20,15,90]])
print(matrix2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [7]:
matrix2.shape

(3, 3)

Creating Matrix with Random Values

In [8]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.30053663 0.78806312 0.38280403]
 [0.86365679 0.75196859 0.84582419]
 [0.7096694  0.09493799 0.47485935]]


In [10]:
# creating matrix with random integer
random_matrix1 = np.random.randint(100, size=(4,5))
print(random_matrix1)

[[11 27 54 33 87]
 [19 74 69 88 19]
 [72 89 48 20 66]
 [87 19 34 86  8]]


Matrix with all the values as 1

In [13]:
matrix3 = np.ones((2,3),dtype = int)
print(matrix3)

[[1 1 1]
 [1 1 1]]


In [14]:
matrix3 = np.ones((10,10),dtype = int)
print(matrix3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or Zero Matrix

In [16]:
null_matrix4 = np.zeros((2,3))
print(null_matrix4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
null_matrix5 = np.zeros((7,7))
print(null_matrix5)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [18]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a matrix

In [19]:
# matrix with random integer values
a = np.random.randint(100,size=(4,5))
print(a)

[[17 84 32 18 86]
 [52 45 55 80  2]
 [74 17 50 34 17]
 [76 30 82 48 36]]


In [20]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[17 52 74 76]
 [84 45 17 30]
 [32 55 50 82]
 [18 80 34 48]
 [86  2 17 36]]
