Importing Numpy Library

In [1]:
import numpy as np

**Matrix Addition**

Two Matrices can be added only if they have the same shape

In [2]:
# creating two matrices
A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])


In [3]:
print(A)

[[2 3]
 [4 5]]


In [4]:
print(B)

[[6 7]
 [8 9]]


In [5]:
A.shape

(2, 2)

In [6]:
B.shape

(2, 2)

Adding two Matrices

In [7]:
sum = A + B

In [8]:
print(sum)

[[ 8 10]
 [12 14]]


In [10]:
  # create two matrices with random values
  matrix_1 = np.random.randint(10,size=(3,3))
  matrix_2 = np.random.randint(20,size=(3,3))

In [11]:
print(matrix_1)

[[9 4 5]
 [2 7 2]
 [7 5 1]]


In [13]:
print(matrix_2)

[[ 3  7 15]
 [ 5 18  9]
 [ 4 18  1]]


In [14]:
sum = np.add(matrix_1,matrix_2)

In [15]:
print(sum)

[[12 11 20]
 [ 7 25 11]
 [11 23  2]]


In [16]:
  # create two matrices with random values
  matrix_3 = np.random.randint(10,size=(3,3))
  matrix_4 = np.random.randint(20,size=(3,4))

In [17]:
sum = np.add(matrix_3,matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

we get this error because shape of matrix_3 and matrix_4 are different

**Matrix Subtraction**

In [18]:
# creating two matrices
A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])

In [19]:
difference = A - B

In [20]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [21]:
  # create two matrices with random values
  matrix_3 = np.random.randint(10,size=(3,3))
  matrix_4 = np.random.randint(20,size=(3,3))

In [22]:
print(matrix_3)

[[4 4 9]
 [0 2 7]
 [2 7 2]]


In [23]:
print(matrix_4)

[[ 9 14  8]
 [12 17 17]
 [12  4 15]]


In [24]:
diff = np.subtract(matrix_3,matrix_4)

In [25]:
print(diff)

[[ -5 -10   1]
 [-12 -15 -10]
 [-10   3 -13]]


**Multiplying a matrix by a scalar**

In [26]:
x = 5
y = np.random.randint(10,size=(4,4))
print(y)

[[8 0 4 8]
 [0 1 0 0]
 [5 3 3 4]
 [1 6 1 1]]


In [27]:
product = np.multiply(x,y)
print(product)

[[40  0 20 40]
 [ 0  5  0  0]
 [25 15 15 20]
 [ 5 30  5  5]]


**Multiplying 2 Matrices**

In [28]:
  # create two matrices with random values
  matrix_3 = np.random.randint(5,size=(3,3))
  matrix_4 = np.random.randint(5,size=(3,4))

In [29]:
print(matrix_3)

[[1 1 3]
 [1 4 1]
 [4 0 2]]


In [30]:
print(matrix_4)

[[4 1 3 0]
 [2 1 3 2]
 [4 1 2 3]]


In [32]:
product = np.dot(matrix_3, matrix_4)

In [33]:
print(product)

[[18  5 12 11]
 [16  6 17 11]
 [24  6 16  6]]


In [34]:
product.shape

(3, 4)

In [35]:
  # create two matrices with random values
  matrix_3 = np.random.randint(5,size=(3,3))
  matrix_4 = np.random.randint(5,size=(4,4))

In [36]:
product = np.dot(matrix_3, matrix_4)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

**Element wise Matrix by a scalar**




In [38]:
  # create two matrices with random values
  matrix_3 = np.random.randint(5,size=(3,3))
  matrix_4 = np.random.randint(5,size=(3,3))

In [40]:
print(matrix_3)

[[1 3 3]
 [2 3 2]
 [1 4 0]]


In [41]:
print(matrix_4)

[[1 1 4]
 [0 3 3]
 [0 1 3]]


In [42]:
product = np.multiply(matrix_3,matrix_4)

In [43]:
print(product)

[[ 1  3 12]
 [ 0  9  6]
 [ 0  4  0]]


In [44]:
  # create two matrices with random values
  matrix_3 = np.random.randint(5,size=(3,3))
  matrix_4 = np.random.randint(5,size=(3,4))

In [45]:
product = np.multiply(matrix_3,matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 