Numpy - numerical python

Advantages of numpy array:

 1. Allow several Mathematical operations
 2. Faster operations

In [1]:
import numpy as np

List Vs Numpy - Time taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list =   [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0011017789999998584


In [7]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

# np_array1 = np.array([i+5 for i in np_array])
np_array += 5

end_time = process_time()

print(end_time - start_time) #time is litte faster as compare to list

0.00017819099999982768


Numpy Arrays

In [8]:
#list

list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [9]:
#numpy array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array) # ndarray - n dimension array

[1 2 3 4 5]


numpy.ndarray

In [14]:
# creating 1 d array

a = np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [15]:
a.shape # no. of column

(5,)

In [16]:
# creating 2 d array
b = np.array([(1,2,3,4,5),(5,6,7,8,9)])
print(b)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [17]:
b.shape # no. of rows and columns

(2, 5)

In [18]:
c = np.array([(1,2,3,4,5),(5,6,7,8,9)],dtype=float)
print(c)

[[1. 2. 3. 4. 5.]
 [5. 6. 7. 8. 9.]]


Initial placeholders in numpy arrays

In [20]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [26]:
# create an identity metrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.11125496 0.42104676 0.45970543 0.70236796]
 [0.93801021 0.25037539 0.34969447 0.78166072]
 [0.73914313 0.45782655 0.55183604 0.66346213]]


In [28]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[97 95 33 57 63]
 [24 41 82 60 13]
 [96 88 29 11 64]]


In [30]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [31]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [33]:
# convert a list to a numpy array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [34]:
c = np.random.randint(10,90,(5,5))
print(c)

[[19 11 62 79 23]
 [44 72 83 10 21]
 [24 51 19 18 76]
 [19 72 66 18 32]
 [63 35 35 49 35]]


In [35]:
# array dimension
print(c.shape)

(5, 5)


In [36]:
# number of dimensions
print(c.ndim)

2


In [38]:
# number of elements in array
print(c.size)

25


In [39]:
# checking the datatype of the values in the array
print(c.dtype)

int64


Mathematical operations on numpy array

In [40]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [42]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [44]:
print(a)
print(b)

[[7 7 1]
 [8 0 7]
 [1 9 5]]
[[16 10 11]
 [15 11 11]
 [11 15 13]]


In [45]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[23 17 12]
 [23 11 18]
 [12 24 18]]
[[ -9  -3 -10]
 [ -7 -11  -4]
 [-10  -6  -8]]
[[112  70  11]
 [120   0  77]
 [ 11 135  65]]
[[0.4375     0.7        0.09090909]
 [0.53333333 0.         0.63636364]
 [0.09090909 0.6        0.38461538]]


In [46]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [47]:
print(a)
print(b)

[[7 9 7]
 [8 0 8]
 [6 5 1]]
[[16 19 14]
 [17 12 16]
 [14 17 12]]


In [48]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[23 28 21]
 [25 12 24]
 [20 22 13]]
[[ -9 -10  -7]
 [ -9 -12  -8]
 [ -8 -12 -11]]
[[112 171  98]
 [136   0 128]
 [ 84  85  12]]
[[0.4375     0.47368421 0.5       ]
 [0.47058824 0.         0.5       ]
 [0.42857143 0.29411765 0.08333333]]


Array Manipulations

In [50]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 8 6]
 [5 5 9]]
(2, 3)


In [51]:
# transpose
b = np.transpose(a)
print(b)
print(b.shape)


[[7 5]
 [8 5]
 [6 9]]
(3, 2)


In [52]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 0 6]
 [5 3 3]]
(2, 3)


In [53]:
c = a.T
print(c)
print(c.shape)

[[6 5]
 [0 3]
 [6 3]]
(3, 2)


In [54]:
# reshaping a array
d = np.random.randint(0,10,(2,3))
print(d)
print(d.shape)

[[1 0 5]
 [2 6 6]]
(2, 3)


In [56]:
e = d.reshape(3,2)
print(e)
print(e.shape)

[[1 0]
 [5 2]
 [6 6]]
(3, 2)
